############################
# --- Required options --- #
############################

# Name of website
title: Nguyen Ngoc Long | Profile
author: Nguyen Ngoc Long
description: 

# Theme
color-scheme: auto
remote_theme: godalming123/minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one